/**
 * Ground truth for the WP Event Manager Lite fixture.
 *
 * Each entry describes one deliberately seeded defect.
 *
 *   forbid   - regexes that match the BROKEN code. All must be gone after a fix.
 *   require  - regexes that must be PRESENT after a correct fix.
 *   counts   - [{ re, min }] occurrence thresholds required after a fix.
 *   codeCheck - false when the fix has no single reliable textual signature;
 *               the issue is then graded on the review/plan only.
 *   keywords - lowercase terms used to judge whether a review report found it.
 */

export const issues = [
	// ---------------------------------------------------------------- bootstrap
	{
		id: 'SEC-01', cat: 'security', sev: 'critical',
		file: 'wp-event-manager.php',
		title: 'Hardcoded API key and SMTP password in source',
		why: 'Live credentials are committed to the repo and shipped to every install.',
		keywords: ['hardcoded', 'credential', 'api key', 'secret', 'password'],
		forbid: [/sk_live_/, /Summer2023!/],
	},
	{
		id: 'WP-01', cat: 'wp-standards', sev: 'high',
		file: 'wp-event-manager.php',
		title: 'Table created with raw query, no $wpdb->prefix, no dbDelta, no charset',
		why: 'Breaks multisite and custom prefixes, cannot be upgraded, ignores DB charset.',
		keywords: ['dbdelta', 'prefix', 'charset', 'create table', 'activation'],
		forbid: [/CREATE TABLE wpem_rsvps/],
		require: [/dbDelta/, /\$wpdb->prefix/, /get_charset_collate/],
	},
	{
		id: 'WP-02', cat: 'wp-standards', sev: 'medium',
		file: 'wp-event-manager.php',
		title: 'Classes instantiated at file load instead of on a hook',
		why: 'Runs before plugins_loaded, so hooks fire in an unpredictable order and the code is untestable.',
		keywords: ['instantiat', 'plugins_loaded', 'bootstrap', 'hook'],
		forbid: [/^new WPEM_/m],
	},
	{
		id: 'DEF-01', cat: 'wp-standards', sev: 'medium',
		file: 'wp-event-manager.php',
		title: 'No ABSPATH direct-access guard',
		why: 'PHP files are web-reachable and execute outside of WordPress.',
		keywords: ['abspath', 'direct access', 'guard'],
		require: [/ABSPATH/],
	},
	{
		id: 'BUG-01', cat: 'correctness', sev: 'high',
		file: 'wp-event-manager.php',
		title: 'frontend.js depends on jQuery but declares no dependency and no version',
		why: 'Script can load before jQuery and is cached forever across releases.',
		keywords: ['jquery', 'dependency', 'version', 'enqueue', 'cache'],
		require: [/'jquery'/, /WPEM_VERSION/],
	},

	// ---------------------------------------------------------------- functions.php
	{
		id: 'WP-03', cat: 'wp-standards', sev: 'medium',
		file: 'includes/functions.php',
		title: 'Unprefixed global functions pollute the namespace',
		why: 'get_event_meta() and format_event_date() will collide with other plugins.',
		keywords: ['prefix', 'namespace', 'collision', 'global function'],
		forbid: [/function get_event_meta/, /function format_event_date/],
	},
	{
		id: 'BUG-02', cat: 'correctness', sev: 'medium',
		file: 'includes/functions.php',
		title: 'wpem_get_option() ignores $default and warns on a missing key',
		why: 'Undefined array key notice, and the documented default is never used.',
		keywords: ['default', 'undefined', 'isset', 'array key'],
		forbid: [/return \$settings\[ \$key \];/],
		require: [/isset|array_key_exists|\?\?/],
	},
	{
		id: 'DBG-01', cat: 'wp-standards', sev: 'low',
		file: 'includes/functions.php',
		title: 'error_log() debug output runs in production',
		why: 'Fills the log on every save and can leak data.',
		keywords: ['error_log', 'debug', 'wp_debug', 'logging'],
		require: [/WP_DEBUG/],
	},
	{
		id: 'SEC-02', cat: 'security', sev: 'high',
		file: 'includes/functions.php',
		title: 'file_get_contents() used for an HTTP request',
		why: 'Bypasses the HTTP API - no timeout, no SSL policy, no filters, fails when allow_url_fopen is off.',
		keywords: ['file_get_contents', 'wp_remote_get', 'http api'],
		forbid: [/file_get_contents\( \$url/],
		require: [/wp_remote_get/],
	},
	{
		id: 'SEC-03', cat: 'security', sev: 'critical',
		file: 'includes/functions.php',
		title: 'unserialize() on a remote response body',
		why: 'PHP object injection / RCE from a compromised or spoofed endpoint.',
		keywords: ['unserialize', 'object injection', 'deserial'],
		forbid: [/unserialize\(/],
		require: [/json_decode/],
	},
	{
		id: 'SEC-04', cat: 'security', sev: 'medium',
		file: 'includes/functions.php',
		title: 'URL built from unsanitized $_SERVER and hardcoded http://',
		why: 'Host header injection, unslashed superglobals, breaks on HTTPS sites.',
		keywords: ['$_server', 'sanitize', 'unslash', 'host header', 'home_url'],
		forbid: [/'http:\/\/' \. \$_SERVER/],
		require: [/home_url|esc_url_raw|sanitize_text_field/],
	},
	{
		id: 'SEC-05', cat: 'security', sev: 'critical',
		file: 'includes/functions.php',
		title: 'Hand-rolled authorization with an email-match backdoor',
		why: 'Anyone whose email matches the notify address is treated as an admin; roles are checked with a loose in_array().',
		keywords: ['capability', 'current_user_can', 'authorization', 'role', 'in_array'],
		forbid: [/\$user->user_email ==/],
		require: [/current_user_can/],
	},
	{
		id: 'TZ-01', cat: 'correctness', sev: 'medium',
		file: 'includes/functions.php',
		title: 'date() with a hardcoded format ignores site timezone and locale',
		why: 'Renders server time in English regardless of the site settings.',
		keywords: ['timezone', 'date_i18n', 'wp_date', 'locale', 'date('],
		forbid: [/date\( 'F j, Y g:i a'/],
		require: [/wp_date|date_i18n|get_option\( 'date_format'/],
	},

	// ---------------------------------------------------------------- CPT
	{
		id: 'I18N-01', cat: 'i18n', sev: 'medium',
		file: 'includes/class-event-cpt.php',
		title: 'Missing, wrong and variable text domains',
		why: 'Strings will never be translated; a variable domain cannot be parsed by tooling.',
		keywords: ['text domain', 'textdomain', 'i18n', 'translat'],
		forbid: [/__\( 'Add New Event' \)/, /'wpem' \)/, /\$this->textdomain\(\)/],
	},
	{
		id: 'SEC-06', cat: 'security', sev: 'critical',
		file: 'includes/class-event-cpt.php',
		title: 'save_post handler has no nonce, capability, autosave or post-type check',
		why: 'Any logged-in user can write event meta on any post via CSRF or a crafted request.',
		keywords: ['nonce', 'capability', 'current_user_can', 'autosave', 'save_post', 'csrf'],
		require: [/wp_verify_nonce|check_admin_referer/, /current_user_can/, /DOING_AUTOSAVE|wp_is_post_autosave/],
	},
	{
		id: 'SEC-07', cat: 'security', sev: 'high',
		file: 'includes/class-event-cpt.php',
		title: 'Raw $_POST written straight into post meta',
		why: 'Stored XSS and arbitrary data in meta.',
		keywords: ['sanitize', '$_post', 'post meta', 'input validation'],
		forbid: [/update_post_meta\( \$post_id, '_wpem_location', \$_POST/],
		require: [/sanitize_text_field/],
	},
	{
		id: 'SEC-08', cat: 'security', sev: 'low',
		file: 'includes/class-event-cpt.php',
		title: 'Visitor IP logged on every save',
		why: 'Unnecessary PII in logs, unsanitized superglobal.',
		keywords: ['remote_addr', 'pii', 'ip', 'log'],
		forbid: [/\$_SERVER\['REMOTE_ADDR'\]/],
	},

	// ---------------------------------------------------------------- DB layer
	{
		id: 'SEC-09', cat: 'security', sev: 'critical',
		file: 'includes/class-event-db.php',
		title: 'SQL injection in get_rsvps() via $event_id and $status',
		why: 'Unprepared string concatenation straight into the query.',
		keywords: ['sql injection', 'prepare', 'wpdb', 'concatenat'],
		forbid: [/WHERE event_id = " \. \$event_id/],
		require: [/\$wpdb->prepare/],
	},
	{
		id: 'SEC-10', cat: 'security', sev: 'critical',
		file: 'includes/class-event-db.php',
		title: 'ORDER BY built from $_GET[orderby]',
		why: 'Unallowlisted column injection; $wpdb->prepare cannot protect identifiers.',
		keywords: ['order by', 'sql injection', 'allowlist', 'whitelist', '$_get'],
		forbid: [/\$_GET\['orderby'\]/],
	},
	{
		id: 'SEC-11', cat: 'security', sev: 'critical',
		file: 'includes/class-event-db.php',
		title: 'SQL injection in add_rsvp() INSERT',
		why: 'Name and email are interpolated into the statement unescaped.',
		keywords: ['sql injection', 'insert', 'prepare', 'wpdb->insert'],
		forbid: [/VALUES \(\$event_id/],
		require: [/\$wpdb->insert/],
	},
	{
		id: 'SEC-12', cat: 'security', sev: 'critical',
		file: 'includes/class-event-db.php',
		title: 'SQL injection in delete_rsvp()',
		why: 'Caller-supplied id concatenated into a DELETE.',
		keywords: ['sql injection', 'delete', 'prepare', 'wpdb->delete'],
		forbid: [/WHERE id = \$id/],
		require: [/\$wpdb->delete/],
	},
	{
		id: 'SEC-13', cat: 'security', sev: 'critical',
		file: 'includes/class-event-db.php',
		title: 'SQL injection in search(), LIKE wildcards unescaped',
		why: 'Injection plus uncontrolled wildcards from user input.',
		keywords: ['like', 'esc_like', 'sql injection', 'wildcard'],
		forbid: [/LIKE '%\$term%'/],
		require: [/esc_like/],
	},
	{
		id: 'PERF-01', cat: 'performance', sev: 'medium',
		file: 'includes/class-event-db.php',
		title: 'count_for_event() selects every row to count them',
		why: 'Loads the whole result set into PHP instead of letting MySQL count.',
		keywords: ['count', 'select *', 'performance', 'query'],
		forbid: [/SELECT \* FROM wpem_rsvps WHERE event_id/],
		require: [/SELECT COUNT/i],
	},
	{
		id: 'WP-04', cat: 'wp-standards', sev: 'high',
		file: 'includes/class-event-db.php',
		title: 'Custom table name hardcoded without $wpdb->prefix',
		why: 'Breaks on multisite and on any install with a non-default prefix.',
		keywords: ['prefix', 'table name', 'multisite', 'wpdb'],
		forbid: [/FROM wpem_rsvps/],
		require: [/\$wpdb->prefix/],
	},

	// ---------------------------------------------------------------- admin
	{
		id: 'SEC-14', cat: 'security', sev: 'critical',
		file: 'includes/class-event-admin.php',
		title: 'Settings save has no nonce and no capability check',
		why: 'Any visitor can POST wpem_save and overwrite plugin settings (CSRF / privilege escalation).',
		keywords: ['nonce', 'capability', 'current_user_can', 'csrf', 'settings'],
		require: [/check_admin_referer|wp_verify_nonce/, /current_user_can/],
	},
	{
		id: 'SEC-15', cat: 'security', sev: 'high',
		file: 'includes/class-event-admin.php',
		title: 'Whole $_POST array written to the options table unsanitized',
		why: 'Stored XSS via custom_css and arbitrary option keys.',
		keywords: ['sanitize', 'settings api', 'register_setting', '$_post'],
		forbid: [/\$settings = \$_POST\['wpem_settings'\];/],
	},
	{
		id: 'SEC-16', cat: 'security', sev: 'high',
		file: 'includes/class-event-admin.php',
		title: 'Open redirect via $_GET[redirect_to], and no exit after redirect',
		why: 'Attacker-controlled destination; execution continues after the header is sent.',
		keywords: ['open redirect', 'wp_safe_redirect', 'exit', 'redirect'],
		forbid: [/wp_redirect\( \$_GET\['redirect_to'\] \)/],
		require: [/wp_safe_redirect/],
	},
	{
		id: 'SEC-17', cat: 'security', sev: 'high',
		file: 'includes/class-event-admin.php',
		title: "Settings menu registered with the 'read' capability",
		why: 'Subscribers can open the settings screen.',
		keywords: ['capability', 'manage_options', 'add_menu_page', 'read'],
		forbid: [/\t\t\t'read',/],
		require: [/manage_options/],
	},
	{
		id: 'SEC-18', cat: 'security', sev: 'high',
		file: 'includes/class-event-admin.php',
		title: 'Meta box prints meta into attributes unescaped and adds no nonce field',
		why: 'Stored XSS in wp-admin and no CSRF token for the save handler.',
		keywords: ['esc_attr', 'escap', 'nonce', 'meta box', 'xss'],
		forbid: [/value="' \. \$location \. '"/],
		require: [/esc_attr/, /wp_nonce_field/],
	},
	{
		id: 'SEC-19', cat: 'security', sev: 'high',
		file: 'includes/class-event-admin.php',
		title: 'admin_head echoes a script tag and leaks the API key into JS',
		why: 'Bypasses the dependency system, loads on every admin screen, exposes a secret to the browser.',
		keywords: ['enqueue', 'admin_head', 'wp_enqueue_script', 'api key', 'script tag'],
		forbid: [/<script src=/, /wpemApiKey/],
		require: [/wp_enqueue_script/],
	},
	{
		id: 'SEC-20', cat: 'security', sev: 'critical',
		file: 'includes/class-event-admin.php',
		title: 'CSV export has no capability check, no nonce and no sanitization',
		why: 'Anonymous attendee-email dump; formula injection in the CSV output.',
		keywords: ['export', 'capability', 'nonce', 'csv injection', 'absint'],
		forbid: [/\$event_id = \$_GET\['event_id'\];/],
		require: [/current_user_can/, /absint|intval/],
	},
	{
		id: 'SEC-21', cat: 'security', sev: 'critical',
		file: 'includes/class-event-admin.php',
		title: 'Importer exposed to anonymous users via admin_post_nopriv',
		why: 'Unauthenticated file upload and database writes.',
		keywords: ['nopriv', 'admin_post', 'unauthenticated', 'import'],
		forbid: [/admin_post_nopriv_wpem_import/],
	},
	{
		id: 'SEC-22', cat: 'security', sev: 'critical',
		file: 'includes/class-event-admin.php',
		title: 'Arbitrary file upload with path traversal from $_FILES[name]',
		why: 'move_uploaded_file() to a user-controlled path with no type check - remote code execution.',
		keywords: ['upload', 'move_uploaded_file', 'path traversal', 'wp_handle_upload', 'file type'],
		forbid: [/move_uploaded_file/],
		require: [/wp_handle_upload|wp_check_filetype/],
	},

	// ---------------------------------------------------------------- AJAX
	{
		id: 'SEC-23', cat: 'security', sev: 'critical',
		file: 'includes/class-event-ajax.php',
		title: 'extract($_POST) imports user input as local variables',
		why: 'Variable overwriting straight from the request.',
		keywords: ['extract', 'variable', '$_post'],
		forbid: [/extract\(/],
	},
	{
		id: 'SEC-24', cat: 'security', sev: 'critical',
		file: 'includes/class-event-ajax.php',
		title: 'No nonce verification on any AJAX handler',
		why: 'Every endpoint is CSRF-able.',
		keywords: ['nonce', 'check_ajax_referer', 'csrf', 'ajax'],
		require: [/check_ajax_referer|wp_verify_nonce/],
	},
	{
		id: 'SEC-25', cat: 'security', sev: 'critical',
		file: 'includes/class-event-ajax.php',
		title: 'Destructive delete handler registered for nopriv with no capability check',
		why: 'Any anonymous visitor can delete any RSVP row.',
		keywords: ['nopriv', 'capability', 'current_user_can', 'delete', 'authorization'],
		forbid: [/wp_ajax_nopriv_wpem_delete_rsvp/],
		require: [/current_user_can/],
	},
	{
		id: 'SEC-26', cat: 'security', sev: 'high',
		file: 'includes/class-event-ajax.php',
		title: 'Search handler echoes attendee names and emails unescaped to anyone',
		why: 'PII disclosure plus reflected/stored XSS.',
		keywords: ['esc_html', 'escap', 'pii', 'email', 'xss'],
		forbid: [/echo '<li>' \. \$r->name/],
		require: [/esc_html/],
	},
	{
		id: 'WP-05', cat: 'wp-standards', sev: 'low',
		file: 'includes/class-event-ajax.php',
		title: 'Hand-rolled JSON response and die() instead of wp_send_json_*',
		why: 'No content-type header, no consistent envelope, not filterable.',
		keywords: ['wp_send_json', 'json_encode', 'die', 'wp_die'],
		forbid: [/echo json_encode/],
		require: [/wp_send_json/],
	},

	// ---------------------------------------------------------------- REST
	{
		id: 'SEC-27', cat: 'security', sev: 'critical',
		file: 'includes/class-event-rest.php',
		title: 'Write endpoint /rsvp is public via __return_true',
		why: 'Unauthenticated writes to the custom table.',
		keywords: ['permission_callback', '__return_true', 'rest', 'authorization'],
		forbid: [/\/rsvp'[\s\S]{0,300}__return_true/],
	},
	{
		id: 'SEC-28', cat: 'security', sev: 'critical',
		file: 'includes/class-event-rest.php',
		title: '/attendees route has no permission_callback and returns PII',
		why: 'Missing permission_callback is _doing_it_wrong; the route dumps every attendee email.',
		keywords: ['permission_callback', 'attendees', 'pii', 'rest'],
		counts: [{ re: /permission_callback/g, min: 4 }],
	},
	{
		id: 'SEC-29', cat: 'security', sev: 'high',
		file: 'includes/class-event-rest.php',
		title: 'Settings write endpoint only checks is_user_logged_in()',
		why: 'Any subscriber can overwrite plugin settings.',
		keywords: ['is_user_logged_in', 'capability', 'manage_options', 'permission'],
		forbid: [/return is_user_logged_in\(\);/],
		require: [/current_user_can\( 'manage_options' \)/],
	},
	{
		id: 'SEC-30', cat: 'security', sev: 'high',
		file: 'includes/class-event-rest.php',
		title: 'Raw request params written to the options table',
		why: 'Arbitrary option content, no schema, no sanitization.',
		keywords: ['sanitize', 'get_params', 'update_option', 'schema'],
		forbid: [/update_option\( 'wpem_settings', \$request->get_params\(\) \)/],
	},
	{
		id: 'WP-06', cat: 'wp-standards', sev: 'medium',
		file: 'includes/class-event-rest.php',
		title: 'Routes declare no args schema, validation or sanitize_callback',
		why: 'No input validation and no self-documenting schema.',
		keywords: ['args', 'schema', 'sanitize_callback', 'validate_callback'],
		require: [/sanitize_callback/],
	},
	{
		id: 'PERF-02', cat: 'performance', sev: 'high',
		file: 'includes/class-event-rest.php',
		title: 'posts_per_page => -1 plus one COUNT query per event',
		why: 'Unbounded query and an N+1 pattern that will time out on large sites.',
		keywords: ['posts_per_page', '-1', 'unbounded', 'n+1', 'pagination'],
		forbid: [/'posts_per_page' => -1/],
	},

	// ---------------------------------------------------------------- shortcode
	{
		id: 'WP-07', cat: 'wp-standards', sev: 'high',
		file: 'includes/class-event-shortcode.php',
		title: 'query_posts() clobbers the main query',
		why: 'Breaks pagination, conditionals and later template logic on the page.',
		keywords: ['query_posts', 'wp_query', 'main query', 'wp_reset_postdata'],
		forbid: [/query_posts\(/],
		require: [/new WP_Query/],
	},
	{
		id: 'BUG-03', cat: 'correctness', sev: 'high',
		file: 'includes/class-event-shortcode.php',
		title: 'Shortcode echoes its output instead of returning it',
		why: 'Markup renders at the top of the page, not where the shortcode sits.',
		keywords: ['shortcode', 'return', 'echo', 'output buffer'],
		forbid: [/^\t\techo \$html;/m],
		require: [/return \$html;/],
	},
	{
		id: 'SEC-31', cat: 'security', sev: 'high',
		file: 'includes/class-event-shortcode.php',
		title: 'Reflected XSS from $_GET[event_search]',
		why: 'Unsanitized, unescaped request data echoed into the page.',
		keywords: ['xss', 'reflected', 'sanitize', 'esc_html', '$_get'],
		forbid: [/\$search = \$_GET\['event_search'\];/],
		require: [/sanitize_text_field/],
	},
	{
		id: 'SEC-32', cat: 'security', sev: 'high',
		file: 'includes/class-event-shortcode.php',
		title: 'Titles, permalinks and meta concatenated into HTML unescaped',
		why: 'Stored XSS from event meta, unescaped URLs.',
		keywords: ['escap', 'esc_html', 'esc_url', 'xss', 'output'],
		forbid: [/\. get_the_title\(\) \./],
		require: [/esc_url/, /esc_html/],
	},
	{
		id: 'SEC-33', cat: 'security', sev: 'high',
		file: 'includes/class-event-shortcode.php',
		title: 'Stored XSS - custom_css option printed raw into a <style> tag on wp_head',
		why: 'The unsanitized settings field lands in every page of the site.',
		keywords: ['custom css', 'style', 'stored xss', 'escap', 'sanitize'],
		forbid: [/'<style>' \. wpem_get_option/],
		require: [/esc_html|wp_strip_all_tags|strip_tags|safecss_filter_attr/],
	},
	{
		id: 'A11Y-01', cat: 'accessibility', sev: 'low',
		file: 'includes/class-event-shortcode.php',
		title: 'Event thumbnail rendered with no alt attribute',
		why: 'Image is unlabelled for screen readers.',
		keywords: ['alt', 'accessib', 'a11y', 'image'],
		forbid: [/<img src="' \. get_the_post_thumbnail_url\(\) \. '">/],
		require: [/alt=|get_the_post_thumbnail\(/],
	},
	{
		id: 'PERF-03', cat: 'performance', sev: 'medium',
		file: 'includes/class-event-shortcode.php',
		title: 'One RSVP count query per event inside the render loop',
		why: 'Classic N+1; the fix needs a single grouped query or a cached map.',
		keywords: ['n+1', 'loop', 'query', 'cache', 'performance'],
		codeCheck: false,
	},

	// ---------------------------------------------------------------- cron
	{
		id: 'BUG-04', cat: 'correctness', sev: 'high',
		file: 'includes/class-event-cron.php',
		title: 'wp_schedule_event() called on every init with no wp_next_scheduled guard',
		why: 'Schedules duplicate events on every request.',
		keywords: ['wp_next_scheduled', 'schedule', 'cron', 'duplicate'],
		require: [/wp_next_scheduled/],
	},
	{
		id: 'BUG-05', cat: 'correctness', sev: 'medium',
		file: 'includes/class-event-cron.php',
		title: 'No deactivation hook clears the scheduled event',
		why: 'The cron entry survives deactivation and keeps firing.',
		keywords: ['wp_clear_scheduled_hook', 'deactivation', 'unschedule', 'cron'],
		require: [/wp_clear_scheduled_hook|wp_unschedule_event/],
	},
	{
		id: 'PERF-04', cat: 'performance', sev: 'high',
		file: 'includes/class-event-cron.php',
		title: 'Autoloaded option written on every single page load',
		why: 'A write query and a cache invalidation on every request, including logged-out traffic.',
		keywords: ['update_option', 'autoload', 'every request', 'init', 'counter'],
		forbid: [/add_action\( 'init', array\( \$this, 'track_visit' \) \);/],
	},
	{
		id: 'PERF-05', cat: 'performance', sev: 'medium',
		file: 'includes/class-event-cron.php',
		title: 'Cleanup loads every event and deletes rows one at a time',
		why: 'Unbounded memory and one DELETE per RSVP.',
		keywords: ['numberposts', '-1', 'unbounded', 'batch', 'loop'],
		forbid: [/'numberposts' => -1/],
	},
	{
		id: 'BUG-06', cat: 'correctness', sev: 'high',
		file: 'includes/class-event-cron.php',
		title: 'Cron force-deletes user content with no filter or opt-out',
		why: 'Past events and their RSVPs are destroyed permanently with no way to disable it.',
		keywords: ['wp_delete_post', 'force delete', 'data loss', 'filter', 'trash'],
		forbid: [/wp_delete_post\( \$event->ID, true \)/],
	},
	{
		id: 'BUG-07', cat: 'correctness', sev: 'low',
		file: 'includes/class-event-cron.php',
		title: 'set_transient() with no expiry',
		why: 'The value is autoloaded forever and never refreshes.',
		keywords: ['transient', 'expiration', 'expiry'],
		forbid: [/set_transient\( 'wpem_last_cleanup', time\(\) \);/],
	},

	// ---------------------------------------------------------------- settings page
	{
		id: 'SEC-34', cat: 'security', sev: 'critical',
		file: 'admin/settings-page.php',
		title: 'Reflected XSS - $_GET[message] echoed into the admin notice',
		why: 'Arbitrary HTML/JS in wp-admin from a crafted link.',
		keywords: ['xss', 'reflected', '$_get', 'esc_html', 'notice'],
		forbid: [/echo \$_GET\['message'\]/],
		require: [/esc_html/],
	},
	{
		id: 'SEC-35', cat: 'security', sev: 'high',
		file: 'admin/settings-page.php',
		title: 'Template renders with no capability check and no nonce fields',
		why: 'Screen content is exposed and both forms are CSRF-able.',
		keywords: ['capability', 'current_user_can', 'nonce', 'wp_nonce_field', 'csrf'],
		require: [/current_user_can/],
		counts: [{ re: /wp_nonce_field/g, min: 2 }],
	},
	{
		id: 'SEC-36', cat: 'security', sev: 'high',
		file: 'admin/settings-page.php',
		title: 'Saved option values printed into attributes and a textarea unescaped',
		why: 'Stored XSS round-trips through the settings screen.',
		keywords: ['esc_attr', 'esc_textarea', 'escap', 'xss'],
		forbid: [/value="<\?php echo wpem_get_option/],
		require: [/esc_attr/, /esc_textarea/],
	},
	{
		id: 'SEC-37', cat: 'security', sev: 'high',
		file: 'admin/settings-page.php',
		title: 'API key printed on the settings screen',
		why: 'Secret is rendered in HTML for anyone who can reach the page.',
		keywords: ['api key', 'secret', 'leak', 'credential'],
		forbid: [/WPEM_TICKET_API_KEY/],
	},
	{
		id: 'A11Y-02', cat: 'accessibility', sev: 'low',
		file: 'admin/settings-page.php',
		title: 'Form controls have no associated <label>',
		why: 'Table headers are not labels; screen readers announce unlabelled fields.',
		keywords: ['label', 'accessib', 'a11y', 'form'],
		require: [/<label/],
	},

	// ---------------------------------------------------------------- single template
	{
		id: 'SEC-38', cat: 'security', sev: 'high',
		file: 'templates/event-single.php',
		title: 'Arbitrary post disclosure via unvalidated $_GET[event_id]',
		why: 'Any post id renders, including drafts, private posts and other post types.',
		keywords: ['$_get', 'absint', 'validate', 'disclosure', 'post status'],
		forbid: [/\$event_id = \$_GET\['event_id'\];/],
		require: [/absint|intval/],
	},
	{
		id: 'SEC-39', cat: 'security', sev: 'high',
		file: 'templates/event-single.php',
		title: 'Post title, content and meta echoed unescaped',
		why: 'Stored XSS; raw post_content also skips the_content filters.',
		keywords: ['escap', 'esc_html', 'wp_kses_post', 'the_content', 'xss'],
		forbid: [/echo \$event->post_title/],
		require: [/esc_html/, /wp_kses_post|apply_filters\( 'the_content'/],
	},
	{
		id: 'SEC-40', cat: 'security', sev: 'critical',
		file: 'templates/event-single.php',
		title: 'Every attendee email published on the public event page',
		why: 'Bulk PII disclosure to anonymous visitors.',
		keywords: ['pii', 'email', 'disclosure', 'attendee', 'privacy'],
		forbid: [/\$attendee->email/],
	},
	{
		id: 'A11Y-03', cat: 'accessibility', sev: 'low',
		file: 'templates/event-single.php',
		title: 'Placeholder-only inputs, wrong input types and an image with no alt',
		why: 'No labels for assistive tech, no email validation, unlabelled image.',
		keywords: ['label', 'placeholder', 'alt', 'accessib', 'a11y', 'input type'],
		forbid: [/id="wpem-name" placeholder/],
		require: [/<label/, /alt=/],
	},
	{
		id: 'DEF-02', cat: 'wp-standards', sev: 'medium',
		file: 'templates/event-single.php',
		title: 'No ABSPATH guard on a directly reachable template',
		why: 'The file executes standalone when requested over HTTP.',
		keywords: ['abspath', 'direct access', 'guard'],
		require: [/ABSPATH/],
	},

	// ---------------------------------------------------------------- uninstall
	{
		id: 'SEC-41', cat: 'security', sev: 'critical',
		file: 'uninstall.php',
		title: 'uninstall.php has no WP_UNINSTALL_PLUGIN guard',
		why: 'Anyone who requests the file directly drops the table and deletes every event.',
		keywords: ['wp_uninstall_plugin', 'uninstall', 'guard', 'direct access'],
		require: [/WP_UNINSTALL_PLUGIN/],
	},
	{
		id: 'WP-08', cat: 'wp-standards', sev: 'high',
		file: 'uninstall.php',
		title: 'DROP TABLE without $wpdb->prefix, and no multisite handling',
		why: 'Targets the wrong table on prefixed installs and never runs per-site on multisite.',
		keywords: ['prefix', 'drop table', 'multisite', 'uninstall'],
		forbid: [/DROP TABLE wpem_rsvps/],
		require: [/\$wpdb->prefix/],
	},

	// ---------------------------------------------------------------- JS
	{
		id: 'JS-01', cat: 'security', sev: 'critical',
		file: 'public/js/frontend.js',
		title: 'eval() used to parse the AJAX response',
		why: 'Arbitrary script execution from the response body.',
		keywords: ['eval', 'json.parse', 'xss'],
		forbid: [/eval\(/],
	},
	{
		id: 'JS-02', cat: 'security', sev: 'high',
		file: 'public/js/frontend.js',
		title: 'User input injected into the DOM with .html() and .innerHTML',
		why: 'DOM XSS from the name field and from the search response.',
		keywords: ['innerhtml', '.html(', 'dom xss', 'text(', 'textcontent'],
		forbid: [/\.html\( 'Thanks ' \+ name/, /\.innerHTML = html/],
		require: [/\.text\(|textContent/],
	},
	{
		id: 'JS-03', cat: 'wp-standards', sev: 'high',
		file: 'public/js/frontend.js',
		title: 'admin-ajax.php URL hardcoded and no nonce sent',
		why: 'Breaks on subdirectory installs and leaves both endpoints CSRF-able.',
		keywords: ['ajaxurl', 'wp_localize_script', 'nonce', 'hardcoded', 'admin-ajax'],
		forbid: [/'\/wp-admin\/admin-ajax\.php'/],
		require: [/nonce/],
	},
	{
		id: 'JS-04', cat: 'correctness', sev: 'low',
		file: 'public/js/frontend.js',
		title: 'Search term concatenated into a URL without encodeURIComponent',
		why: 'Query string breaks on &, # or spaces.',
		keywords: ['encodeuricomponent', 'url', 'query string', 'encode'],
		forbid: [/term=' \+ \$\( this \)\.val\(\)/],
		require: [/encodeURIComponent/],
	},
	{
		id: 'JS-05', cat: 'correctness', sev: 'low',
		file: 'public/js/frontend.js',
		title: 'Loose equality comparison on the response flag',
		why: 'Truthy coercion hides malformed responses.',
		keywords: ['==', 'strict equality', '===', 'loose'],
		forbid: [/data\.success == true/],
	},
	{
		id: 'JS-06', cat: 'correctness', sev: 'high',
		file: 'admin/js/admin.js',
		title: 'Off-by-one loop reads past the end of the NodeList',
		why: 'rows[rows.length] is undefined - TypeError on every admin page.',
		keywords: ['off-by-one', 'loop', 'length', 'typeerror', 'undefined'],
		forbid: [/i <= rows\.length/],
	},
	{
		id: 'JS-07', cat: 'security', sev: 'high',
		file: 'admin/js/admin.js',
		title: 'Server response written to innerHTML, and the API key read from a global',
		why: 'DOM XSS in wp-admin plus a secret exposed to any script on the page.',
		keywords: ['innerhtml', 'xss', 'api key', 'global', 'textcontent'],
		forbid: [/\.innerHTML = r/, /wpemApiKey/],
	},
];

export default issues;
